### PR TITLE
Add truncated games csv file

### PR DESCRIPTION
**Pull request by javier-aguilar**
I've added a truncated games csv file so we can use for testing

### CODE REVIEW

**Comment by javier-aguilar** [comment]
I also made sure to include different seasons and season types.

**Comment by Shock253** [comment]
looks good to me, that should be enough to test with

**Comment by mlynch5187** [comment]
I agree with Ethan, this will work just fine!

**Comment by Shock253** [comment]
Do you have winning, losing, and tied games?

**Comment by Shock253** [comment]
alright looks good

**Pull request merged**
